capp/about/__init__.py
#

capp/about/routes.py
from flask import render_template, Blueprint

about=Blueprint('about',__name__)

@about.route('/about')
def about_home():
  return render_template('about.html')

capp/carbon_app/routes.py
from flask import render_template, Blueprint, request, redirect, url_for, flash
from capp.models import Transport
from capp import db
from datetime import timedelta, datetime
from flask_login import login_required, current_user
from capp.carbon_app.forms import BusForm, CarForm, PlaneForm, FerryForm, MotorcycleForm, WalkForm
from capp.carbon_app.forms import TrainForm
import json

carbon_app=Blueprint('carbon_app',__name__)

#Emissions factor per transport in kg per passenger km
#Data from: http://efdb.apps.eea.europa.eu/?source=%7B%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%2C%22display_type%22%3A%22tabular%22%7D
efco2={'Bus':{'Diesel':0.027 ,'Biodiesel':0.014,'Electric':0.013},
    'Car':{'Petrol':0.04689,'Diesel':0.05711,'Electric':0.01046},
    'Airplane':{'Gasoline':0.19766667},
    'Ferry':{'Heavy Fuel Oil':0.170, 'Electric':0.00608},
    'Motorcycle':{'Gasoline':0.0852},
    'Train':{'Electric':0.01, 'Diesel':0.091},
    'Walk':{'No Fossil Fuel':0}}

efch4={'Bus':{'Diesel':0 ,'Biodiesel':0,'Electric':0},
    'Car':{'Petrol':0,'Diesel':0,'Electric':0},
    'Airplane':{'Gasoline':0},
    'Ferry':{'Heavy Fuel Oil':0, 'Electric':0},
    'Motorcycle':{'Gasoline':0,},
    'Train':{'Electric':0, 'Diesel':0},
    'Walk':{'No Fossil Fuel':0}}


#Carbon app, main page
@carbon_app.route('/carbon_app')
@login_required
def carbon_app_home():
    return render_template('carbon_app/carbon_app.html', title='carbon_app')

#New entry bus
@carbon_app.route('/carbon_app/new_entry_bus', methods=['GET','POST'])
@login_required
def new_entry_bus():
    form = BusForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Bus'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_bus.html', title='new entry bus', form=form)

#New entry car
@carbon_app.route('/carbon_app/new_entry_car', methods=['GET','POST'])
@login_required
def new_entry_car():
    form = CarForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Car'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_car.html', title='new entry car', form=form)    

#New entry plane
@carbon_app.route('/carbon_app/new_entry_plane', methods=['GET','POST'])
@login_required
def new_entry_plane():
    form = PlaneForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Airplane'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_plane.html', title='new entry plane', form=form)  

#New entry train
@carbon_app.route('/carbon_app/new_entry_train', methods=['GET','POST'])
@login_required
def new_entry_train():
    form = TrainForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Train'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_train.html', title='new entry train', form=form)  

#New entry ferry
@carbon_app.route('/carbon_app/new_entry_ferry', methods=['GET','POST'])
@login_required
def new_entry_ferry():
    form = FerryForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Ferry'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_ferry.html', title='new entry ferry', form=form)     

#New entry motorbike
@carbon_app.route('/carbon_app/new_entry_motorbike', methods=['GET','POST'])
@login_required
def new_entry_motorbike():
    form = MotorcycleForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Motorcycle'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_motorbike.html', title='new entry motorbike', form=form) 

#New entry walk
@carbon_app.route('/carbon_app/new_entry_walk', methods=['GET','POST'])
@login_required
def new_entry_walk():
    form = WalkForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Walk'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_walk.html', title='new entry walk', form=form)

#Your data
@carbon_app.route('/carbon_app/your_data')
@login_required
def your_data():
    #Table
    entries = Transport.query.filter_by(author=current_user). \
        filter(Transport.date> (datetime.now() - timedelta(days=5))).\
        order_by(Transport.date.desc()).order_by(Transport.transport.asc()).all()
    
    #Emissions by category
    emissions_by_transport = db.session.query(db.func.sum(Transport.total), Transport.transport). \
        filter(Transport.date > (datetime.now() - timedelta(days=5))).filter_by(author=current_user). \
        group_by(Transport.transport).order_by(Transport.transport.asc()).all()
    emission_transport = [0, 0, 0, 0, 0, 0, 0, 0, 0]
    first_tuple_elements = []
    second_tuple_elements = []
    for a_tuple in emissions_by_transport:
        first_tuple_elements.append(a_tuple[0])
        second_tuple_elements.append(a_tuple[1])

    if 'Bus' in second_tuple_elements:
        index_bus = second_tuple_elements.index('Bus')
        emission_transport[1]=first_tuple_elements[index_bus]
    else:
        emission_transport[1]

    if 'Car' in second_tuple_elements:
        index_car = second_tuple_elements.index('Car')
        emission_transport[2]=first_tuple_elements[index_car]
    else:
        emission_transport[2]

    if 'Ferry' in second_tuple_elements:
        index_ferry = second_tuple_elements.index('Ferry')
        emission_transport[3]=first_tuple_elements[index_ferry]
    else:
        emission_transport[3]

    if 'Motorbike' in second_tuple_elements:
        index_motorbike = second_tuple_elements.index('Motorbike')

capp/home/routes.py
from flask import render_template, Blueprint
from capp.models import User, Transport

home=Blueprint('home',__name__)

@home.route('/')
@home.route('/home')
def home_home():
  return render_template('home.html')

capp/methodology/routes.py
from flask import render_template, Blueprint

methodology=Blueprint('methodology',__name__)

@methodology.route('/methodology')
def methodology_home():
  return render_template('methodology.html', title='methodology')

capp/users/routes.py
from flask import render_template, Blueprint, redirect, flash, url_for, request
from capp.users.forms import RegistrationForm, LoginForm
from capp.models import User
from capp import db, bcrypt
from flask_login import login_user, current_user, logout_user

users=Blueprint('users',__name__)

@users.route('/register', methods=['GET','POST'])
def register():
  form = RegistrationForm()
  if current_user.is_authenticated:
        return redirect(url_for('home.home_home'))
  if form.validate_on_submit():
      user_hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
      user = User(username=form.username.data, email=form.email.data, password=user_hashed_password)
      db.session.add(user)
      db.session.commit()
      flash('Your account has been created! Now, you are able to login!', 'success')
      return redirect(url_for('users.login'))
  return render_template('users/register.html', title='register', form=form)

@users.route('/login', methods=['GET','POST'])
def login():
  form = LoginForm()
  if current_user.is_authenticated:
        return redirect(url_for('home.home_home'))
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
        login_user(user, remember=form.remember.data)
        next_page = request.args.get('next')
        flash('You have logged in! Now, you can start to use our Carbon App!', 'success')
        return redirect(next_page) if next_page else redirect(url_for('home.home_home'))
    else:
        flash('Login Unsuccessful. Please check email and password!', 'danger') 
  return render_template('users/login.html', title='login', form=form)

@users.route('/logout')
def logout():    
    logout_user()
    return redirect(url_for('home.home_home'))


capp/templates/home.html
{% extends "layout.html" %}
{% block content %}

  <div class="section_home">
        <div class="container"> 
          <div class="top_home">
          <div class="home_heading">
          Innovating your carbon footprint
          </div>
        <div class="home_heading_info">
          <p>
            Welcome to our cutting-edge carbon tracker for businesses. 
            We're here to revolutionize how you manage your carbon footprint. 
            With real-time insights and actionable data, we empower you to drive meaningful change towards sustainability. 
            Let's innovate your carbon footprint together.
        </p>
        </div>
        <div class="home_heading_info_more">
          <div>
            <a href="{{url_for('methodology.methodology_home')}}">See how <i class="fa-solid fa-arrow-right"></i></a>
          </div>
        </div>
        
      </div>
      </div>
    <div class="container">
      <section class="container-one">
        <img src="{{url_for('static',filename='pictures/data-table.png')}}" loading="eager" width="400px" sizes="(max-width: 400px) 60vw, 400px" alt="Two people at a desk using sustainability software." class="lifestyle-image">
        <img src="{{url_for('static',filename='pictures/linjediagram.png')}}" loading="eager" width="400px" sizes="(max-width: 400px) 60vw, 400px" alt="Card showing a companys total emissions: 3,174 MT CO2e" width="318px" class="emissions-card">
        <img src="{{url_for('static',filename='pictures/piechart.png')}}" loading="eager" width="400px" sizes="(max-width: 400px) 60vw, 400px" alt="Sample Sustain.Life impact dashboard showing emissions, spend, and offsets " class="impact-chart">
        <img src="{{url_for('static',filename='pictures/data-car.png')}}" loading="eager" width="400px" sizes="(max-width: 400px) 60vw, 400px" alt="Sustain.Life emissions card showing building-related emissions" class="category-card">
      </section>
    <div class="container">
      <section class="container-home-two">
        <h4 class="container-home-two-text">
          Developed together and across our partners
        </h4>
        <div>
          <img src="https://www.hvl.no/globalassets/hvl-internett/bilde/logo/hvl_logo_en_neg.png" alt="logo-hvl" class="logo-hvl">
          <img src="{{url_for('static',filename='pictures/GitHub_Logo_White.png')}}" alt="logo-github" class="logo-github">
        </div>
      </section>
    </div>
    </div>
  </div>
    <section class="home-second-box">
      <div class="container">
      <div class="small-heading-home2">
        HOW IT WORKS
      </div>
      <div class="big-heading-home2">
        Analyzing-<br>Calculating-<br>your footprint
      </div>
      <div class="container"> 
        <div class="top_home">
      <div class="home_heading_info2">
        <p style="color: #212529;">
          Our Calculator tool is designed to help you understand and reduce your carbon footprint by providing insights into your transportation choices. Here's how it works: <br><br>
          You'll start by selecting your preferred mode of transportation and entering the distance you travel using that mode. Our app will then calculate your carbon emissions based on your input. <br><br>
          After you've entered your data, our app will generate a comprehensive graph showing your total emissions and the breakdown of emissions by transportation mode. This will give you a clear overview of your environmental impact and help you identify areas where you can make greener choices. <br><br>
          Thank you for using our app! We hope it empowers you to make more sustainable lifestyle choices.
      </p>
      </div>
      <div class="home_heading_info_more">
        <div class="demo_box">
          <div class="btn_nav_demo">
             <a href="{{url_for('carbon_app.your_data')}}">Calculator</a>
          </div>
         </div>
        <div>
          <a href="{{url_for('methodology.methodology_home')}}" style="color: #212529;">See how<i class="fa-solid fa-arrow-right"></i></a>
        </div>
      </div>
      
    </div>
    </div>
    </div>
    </section>

    <section class="home-third-box">
      <div class="container">
        <div class="yellow-container">
        <div class="big-heading-home3">
          Change your<br>carbon footprint<br>now.
        </div>
        <div>
          <img class="bus-picture" style="width: 300px; padding: 25px;" src="{{url_for('static',filename='pictures/traveling-photo.jpeg')}}" alt="">
        </div>
      </div>
      </div>
    </section>

</body>
</html>

{% endblock content %}

capp/templates/layout.html
<!DOCTYPE html>
<html> 
    <head>
      <!-- Font Awesome code -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

      <!--Import the Bootstrap CSS file:-->
      <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
      />
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
      />

      <!-- Matjax -->
      <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
      <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

      
      <!-- CSS code -->
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layout.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='methodology.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='carbon_app.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='about.css') }}">

      

      <!-- To activate media queries in devices -->
      <meta name="viewport" content="user-scalable=yes, width=device-width, initial-scale=1">

      <!--For the plots-->
      <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
      <!-- <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> -->

        {% if title %}
            <title>{{ title }}</title>
        {% else %}
            <title>home</title>
        {% endif %}
        
    </head>
    <body>
     <section class="section_carbon_app_navbar">
  <div class="container">
    <div class="carbon_app_navbar1">
      <div class="logo">
        <a href="/">
          <span class="text-logo">FOOTPRINT</span>
        </a>
      </div>
      {% if current_user.is_authenticated %}
      <div class="carbon_app_navbar_ul1">
        <ul>
          <li>
            <a href="{{url_for('carbon_app.carbon_app_home')}}">Product</a>
          </li>
          <li>
            <a href="{{url_for('methodology.methodology_home')}}">Methodology</a>
          </li>
          <li>
            <a href="{{url_for('about.about_home')}}">About</a>
          </li> 
          <li>
            <a href="{{url_for('carbon_app.your_data')}}">Your Data</a>
          </li>

                  </ul>
                </div>
                      <div class="nav-right">
                        <div class="btn-nav1">
                          <a href="{{url_for('users.logout')}}">Log out</a>
                        </div>
                        <div class="demo_box">
                          <div class="btn_nav_demo">
                            <a href="{{url_for('carbon_app.carbon_app_home')}}">Calculator</a>
                          </div>
                        </div>
                      </div>
                    </div>
                
                  {% else %}
                  <div class="carbon_app_navbar_ul1">
                    <ul>
                      <li>
                          <a href="{{url_for('carbon_app.carbon_app_home')}}">Product</a>
                      </li>
                      <li>
                          <a href="{{url_for('methodology.methodology_home')}}">Methodology</a>
                      </li>
                      <li>
                        <a href="{{url_for('about.about_home')}}">About</a>
                      </li>
                  </ul>
                </div>
                      <div class="nav-right">
                        <div class="btn-nav1">
                          <a href="{{url_for('users.register')}}">Register</a>
                        </div>
                        <div class="demo_box">
                          <div class="btn_nav_demo">
                            <a href="{{url_for('carbon_app.carbon_app_home')}}">Calculator</a>
                          </div>
                        </div>
                      </div>
                    </div>
              {% endif %}
            </div>
          </div>
        </section>

        {% block content %} {% endblock %}

        <section class="section_footer">
          <div class="container">
            <div class="footer">
              <h1 style="font-weight: 600;">
                Footprint 
                <a href="#" style="text-decoration: none; color: rgb(214, 61, 61);">
                  App
                </a>
              </h1>
            </div>
          </div>
        </section>
        </div>     
        <script src="{{ url_for('static', filename='script.js')}}"></script>

        <!-- Bootstrap -->
        <!-- Question Accordion -->
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
          crossorigin="anonymous"
        ></script>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        
    </body>
</html>

capp/templates/methodology.html
{% extends "layout.html" %}
{% block content %}

<section>
    <div class="overlay_text">
      <div class="container" style="width: 100%; ">
        <div class="top_home" style="margin-bottom: 0;">
          <div class="home_heading">
            Our Methodology
          </div>
          <div class="home_heading_info" style="width: 80%;">
            <p style="text-align:left;">
                Welcome to the inner workings of our carbon footprint calculator! We're excited to show you how we've put everything together.

At the core of our calculator are trusted sources like Fremtiden i våre hender (The Future in Our Hands) and Statistics Norway (SSB). We've tapped into their data to fuel our calculator, ensuring reliability and accuracy in every calculation.
<br><br>

While we've gone into more detail in our paper, we've simplified things here to make it easy for you to follow along. Basically, we've gathered a bunch of numbers and formulas to estimate your carbon footprint.

Our aim? To empower you to make greener choices and do your part for the planet. <br><br> <strong>You can read our paper by clicking the button below! </strong> So, let's take a peek behind the curtain and see how it all comes together!
            </p>

            <div class="demo_box">
                <div class="btn_nav_demo">
                    <a href="https://methodology24carbonapphvl.tiiny.site">Paper</a>
                </div>
            </div> 

          </div>
        </div>
      </div>
    </div>
  </section>
  
  
<!-- Methodology -->
<section class="section_body_methodology">
    <div class="container">
  
        <div class="methodology">
            <h1 style="text-align:center; align-items: center; ">Our Formulas</h1>
        </div>
  
        <!-- First row with two boxes -->
    <div class="methodology">
        <div class="row">
          <div class="box">
            <h4>The General Formula:</h4>
            \[\text{CO}_{2}=d*\frac{ef}{p}\]
            <br>
            In which:
            \[\text{CO}_2 \text{ = carbon emissions in grams} \]
            \[\text{d} \text{ = distance traveled in km} \]
            \[\text{ef} \text{ = emission factor in CO}_2 \text{/km} \]
            \[\text{p} \text{ = amount of passengers} \]</p>
          </div>
          <div class="box">
            <h4>General Formula for Electric Vehicles:</h4>
             \[ \text{Ef = x * Ec} \]
                <br>
                <br>

                In which:
                \[\text{ef} \text{ = emission factor in gCO}_2 \text{/km} \]
                \[\text{x} \text{ = the distance traveled in kilometers} \text{} \]
                \[\text{ec} \text{ = emission factor in grams of gCO}_2 \text{/km} \]</p>
          </div>
        </div>
      </div>
  
      <div class="methodology" style="display:block;">
        <h1 style="text-align:start;"> Our Numbers</h1>
        <p>
            Now that we have presented our general formula to our calculations, we now present the numbers we have
            gathered through our research on the matter:
        </p>
    </div>

    <div class="methodology">
        <div class="row">
          <div class="box_table1">
            <h3>FERRY</h3>
            <p> Ferris contributes significantly to emissions. Norway has initiated a project named "to zero," aiming to implement fully electric ferries. However, presently, the ferries continue to operate on diesel. According to Fremtiden I Våre Hender, their emissions amount to <strong>226 grams of CO2 per passenger-kilometer.</strong></p>
            <!-- Content for Ferry -->
          </div>
          <div class="box_table1">
            <h3>CAR</h3>
            <p>The Norwegian government's incentives have propelled electric vehicle sales, resulting in Norway leading globally in electric cars per capita. Emissions vary by car size, with <strong> electric cars averaging 4,943 g CO2/km </strong>. Despite electric car adoption, many gasoline and diesel cars remain in use, where <strong> emits 57.11 g CO2/km, and diesel emits 46.89 g CO2/km.</strong></p>
            <!-- Content for Car -->
          </div>
        </div>
      </div>
      
      <div class="methodology">
        <div class="row">
          <div class="box_table1">
            <h3>MOTORCYCLE</h3>
            <p>Motorcycles, running on gasoline, are often seen as environmentally friendly due to their size and fuel efficiency. According to Fedoryshyn (2016),<strong> motorcycles emit 85.2g of CO2 per kilometer driven.</strong></p>
            <!-- Content for Motorcycle -->
          </div>
          <div class="box_table1">
            <h3>TRAIN</h3>
            <p>As per VY's sustainability report for 2023, <strong> electric trains emit 10 grams of CO2 per person, whereas diesel-powered trains emit 91 grams of CO2 per kilometer.</strong> Our calculations are based on emissions data specific to Norway.</p>
            <!-- Content for Train -->
          </div>
        </div>
      </div>
      
      <div class="methodology">
        <div class="row">
          <div class="box_table1">
            <h3>BUS</h3>
            <p>Our calculations for buses are derived from the same report used for trains, namely VY's sustainability report for 2023. According to this data, buses emit <strong>27 grams of CO2 per kilometer when powered by diesel</strong>, <strong>14 grams of CO2 per kilometer with biodiesel</strong>, and <strong>13 grams of CO2 per kilometer when electrically powered</strong>.</p>
            <!-- Content for Bus -->
          </div>
          <div class="box_table1">
            <h3>AIRPLANE</h3>
            <p>When considering air travel, we classify flights by class: economy, economy premium, and business. Our main data source for CO2 emissions from airplanes is the "Klimasmart Semester" report. From this report, we derived an average emission rate for different classes, which we use in our calculations: <strong>197,667 g CO2 per kilometer</strong>.</p>
            <!-- Content for Airplane -->
          </div>
        </div>
      </div>
      


</div>
</section>
  
  

</body>
</html>

{% endblock content %}